[tool.poetry]
name = "ghostcoder"
version = "0.0.13"
description = ""
authors = ["Albert Örwall <albert@a20g.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
openai = "1.6.1"
#langchain = "^0.0.344"
pydantic = "1.10.13"
#pathspec = "^0.11.1"
#gitpython = "^3.1.31
tiktoken = "0.5.2"
tree-sitter-languages = "1.9.1"
#llama-index = "^0.9.10"
#streamlit = "^1.28.1"
#chromadb = "^0.4.18"
#flask = "^3.0.0"
#pymongo = "^4.6.1"
#colorlog = "^6.8.0"

[tool.poetry.group.dev.dependencies]
ipywidgets = "^8.1.1"
pyfakefs = "^5.2.3"
ipython = "^8.16.1"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
