[tool.poetry]
name = "epicsplit"
version = "0.0.1"
description = ""
authors = ["Albert Örwall <albert@a20g.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pytest = "8.1.1"
typer = "0.9.0"
datasets = "2.18.0"

tiktoken = "0.6.0"
tree-sitter-languages = "1.10.2"

openai = "1.14.2"

llama-index = "0.10.22"
llama-index-embeddings-openai = "0.1.7"
llama-index-readers-file = "0.1.12"

# TODO: Shouldn't depend on chromadb
llama-index-vector-stores-chroma = "0.1.6"
chromadb = "0.4.24"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
