[tool.poetry]
name = "moatless"
version = "0.0.1"
description = ""
authors = ["Albert Örwall <albert@a20g.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"

datasets = "2.19.1"

litellm = "1.37.16"
instructor = "1.3.3"

tiktoken = "0.7.0"
networkx = "3.3"

tree-sitter = "0.22.3"
tree-sitter-python = "0.21.0"
tree-sitter-java = "0.21.0"

rapidfuzz = "3.9.3"

openai = "1.30.1"

llama-index = "0.10.37"
llama-index-embeddings-openai = "0.1.9"
llama-index-embeddings-voyageai = "0.1.4"
llama-index-readers-file = "0.1.22"

faiss-cpu = "1.8.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-mock = "3.14.0"
python-dotenv = "1.0.1"
mypy = "1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
