[tool.poetry]
name = "moatless"
version = "0.0.1"
description = ""
authors = ["Albert Örwall <albert@a20g.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pytest = "8.1.1"
typer = "0.9.0"
datasets = "2.18.0"


litellm = "1.34.12"

tiktoken = "0.6.0"

tree-sitter = "0.21.3"
tree-sitter-python = "0.21.0"

openai = "1.14.2"

llama-index = "0.10.22"
llama-index-embeddings-openai = "0.1.7"
llama-index-readers-file = "0.1.12"

# TODO: Shouldn't depend on chromadb
llama-index-vector-stores-chroma = "0.1.5"
llama-index-vector-stores-deeplake = "0.1.2"
chromadb = "0.4.22"
deeplake = "3.8.27"

# TODO: Benchmark specific dependencies
python-dotenv = "1.0.1"
azure-storage-blob = "12.19.1"
et = "^0.0.2"
ipython = "^8.23.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
